# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "remote" {
    hostname = "app.terraform.io" # Change this to your hostname for TFE
    organization = "ccoe-ttech"
    workspaces {
      name = "terragrunt"
    }
  }
}
